commit-binaries: handle github hosted remotes for optee
Both optee-os and optee-test are directly fetched from github. Because
of this, we currently see:

error: No such remote 'baylibre'
error: No such remote 'baylibre'
error: No such remote 'baylibre'

Handle those remotes as well.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>