build_optee: add CFG_DT flag
From OP-TEE 4.1.0, CFG_DT flag must be added, otherwise we have this
compilation error:
core/arch/arm/kernel/boot.c:1501: undefined reference to `dt_getprop_as_number'

Notes:
CFG_DT flag may need to be added by default in core/arch/arm/plat-k3/conf.mk

Signed-off-by: Julien Masson <jmasson@baylibre.com>